/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.google.gson.Gson;
import dao.ConnectionProvider;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
import utility.BDUtility;

/**
 *
 * @author nuzhat
 */
public class GenerateQr extends javax.swing.JFrame {

    /**
     * Creates new form GenerateQr
     */
    public GenerateQr() {
        initComponents();
        BDUtility.setImage(this,"images/abc1.jpg",1101, 535);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4,4,4,4,Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        btnSaveQr = new javax.swing.JButton();
        btnSaveQrAt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1101, 501));
        setMinimumSize(new java.awt.Dimension(1101, 501));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Generate QR");

        btnExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit1.setText("x");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Gender", "Email", "Contact", "Address", "State", "Country", "Registration id"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        btnSaveQr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveQr.setText("Save Qr");
        btnSaveQr.setPreferredSize(new java.awt.Dimension(142, 33));
        btnSaveQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQrActionPerformed(evt);
            }
        });

        btnSaveQrAt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveQrAt.setText("Save Qr At");
        btnSaveQrAt.setPreferredSize(new java.awt.Dimension(142, 33));
        btnSaveQrAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQrAtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(453, 453, 453)
                        .addComponent(btnExit1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveQr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSaveQrAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit1)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveQrAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveQr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnSaveQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQrActionPerformed
        try{
         if(out == null){
             JOptionPane.showMessageDialog(this, "no Qr Generated!!");
             return;
         } 
         String defaultDir = BDUtility.getPath("qrCodes");
         File directory = new File(defaultDir);
         if(!directory.exists()){
             directory.mkdirs();
         }
         File dfaultFile = new File (directory, email+".jpg");
         try{
            java.nio.file.Files.write(dfaultFile.toPath(),out.toByteArray());
            JOptionPane.showMessageDialog(null, "Qr Code Saved Successfully!!!");
         
            String qrCodePath = BDUtility.getPath("qrCodes")+"\\"+email+".jpg";
            saveQrCodeToDatabase(email, qrCodePath);
             System.out.println("qr path"+qrCodePath);
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null, "Error Saving Qr Code!!","Error",JOptionPane.ERROR_MESSAGE);
         }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Something went wrong!!");
        }
    }//GEN-LAST:event_btnSaveQrActionPerformed
    private void saveQrCodeToDatabase(String email, String qrCodeData) {
    Connection con = null;
    PreparedStatement ps = null;

    try {
        // Establish database connection
        con = ConnectionProvider.getCon();

        String query = "UPDATE userdetails SET qrcode = ? WHERE email = ?";

        
        ps = con.prepareStatement(query);
        ps.setString(1, qrCodeData);  
        ps.setString(2, email);  

       
        int rowsUpdated = ps.executeUpdate();

        
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "QR Code saved in database successfully!!");
        } else {
            JOptionPane.showMessageDialog(null, "No record found for the given email.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error saving QR Code to database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (ps != null) {
                ps.close();
            }
            if (con != null) {
                con.close();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        try{
        Connection connection = ConnectionProvider.getCon();
        Statement statement = connection.createStatement();
        //statement.executeQuery("select * from userdetails");
        ResultSet resultSet = statement.executeQuery("select * from userdetails");
        while(resultSet.next()){
            model.addRow(new Object[]{
            resultSet.getString("id"),
            resultSet.getString("Name"),
            resultSet.getString("Gender"),
            resultSet.getString("Email"),
            resultSet.getString("Contact"),
            resultSet.getString("Address"),
            resultSet.getString("State"),
            resultSet.getString("Country"),
            resultSet.getString("uniqueregid")
            });
        }
        }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "something went wrong!!");
        }
    }//GEN-LAST:event_formComponentShown
    ByteArrayOutputStream out  = null;
    String email = null;
    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
       int index = userTable.getSelectedRow();
       TableModel model = userTable.getModel();
       
       String id = model.getValueAt(index, 0).toString();
       String name = model.getValueAt(index, 1).toString();
       email = model.getValueAt(index, 3).toString();
       String registrationId = model.getValueAt(index,8).toString();
       
       Map<String,String> data = new HashMap<>();
       data.put("id", id);
       data.put("name", name);
       data.put("email",email);
       data.put("registrationId",registrationId);
       
       Gson gson = new Gson();
       String jsonData = gson.toJson(data);
       
       out = QRCode.from(jsonData).withSize(322,286).to(ImageType.PNG).stream();
       try{
           byte[] imageData = out.toByteArray();
           ImageIcon icon = new ImageIcon(imageData);
           lblImage.setIcon(icon);
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }//GEN-LAST:event_userTableMouseClicked

    private void btnSaveQrAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQrAtActionPerformed
        try{
            if(out== null){
                JOptionPane.showMessageDialog(null,"no Qr is Generated!");
                return;
            }
           JFileChooser fileChooser = new JFileChooser();
           fileChooser.setDialogTitle("Save Qr Code at");
           fileChooser.setSelectedFile(new File(email+".png"));
           int userSelection = fileChooser.showSaveDialog(this);
           if(userSelection == JFileChooser.APPROVE_OPTION){
               File fileTOSave = fileChooser.getSelectedFile();
              try{
                  java.nio.file.Files.write(fileTOSave.toPath(),out.toByteArray());
                  JOptionPane.showMessageDialog(this, "Qr Code saved Successfully!!!");
              } catch(Exception ex){
                  JOptionPane.showMessageDialog(this, "Error saving Qr Code.","Error",JOptionPane.ERROR_MESSAGE );
              }
           }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Something went wrong!!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveQrAtActionPerformed
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateQr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnSaveQr;
    private javax.swing.JButton btnSaveQrAt;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
