/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.BDUtility;

/**
 *
 * @author nuzhat
 */
public class ViewAttendance extends javax.swing.JFrame {

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/abc1.jpg", 1101, 509);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));

        DateChooserFrom.setDateFormatString("yyyy-MM-dd");
        DateChooserTo.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTabel = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btnExit2 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        DateChooserTo = new com.toedter.calendar.JDateChooser();
        DateChooserFrom = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        presentLBL = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        absentLBL = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        CheckBoxContact = new javax.swing.JCheckBox();
        CheckBoxAddress = new javax.swing.JCheckBox();
        CheckBoxState = new javax.swing.JCheckBox();
        CheckBoxCountry = new javax.swing.JCheckBox();
        CheckBoxUniqueRegId = new javax.swing.JCheckBox();
        btnResetFilters = new javax.swing.JButton();

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DeleteUser");

        btnExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit1.setText("x");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setText("Contact");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1101, 501));
        setMinimumSize(new java.awt.Dimension(1101, 501));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        userTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTabel);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Attendance Track");

        btnExit2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit2.setText("x");
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        DateChooserTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooserToPropertyChange(evt);
            }
        });

        DateChooserFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooserFromPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("On/From");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("To");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Search");

        presentLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        presentLBL.setText("Present :");

        lblPresent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(51, 255, 0));
        lblPresent.setText("--------");

        absentLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        absentLBL.setText("Absent :");

        lblAbsent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 51, 0));
        lblAbsent.setText("--------");

        CheckBoxContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxContact.setText("Contact");
        CheckBoxContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxContactItemStateChanged(evt);
            }
        });

        CheckBoxAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxAddress.setText("Address");
        CheckBoxAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxAddressItemStateChanged(evt);
            }
        });
        CheckBoxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxAddressActionPerformed(evt);
            }
        });

        CheckBoxState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxState.setText("State");
        CheckBoxState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxStateItemStateChanged(evt);
            }
        });

        CheckBoxCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxCountry.setText("Country");
        CheckBoxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxCountryItemStateChanged(evt);
            }
        });

        CheckBoxUniqueRegId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxUniqueRegId.setText("Unique Reg ID");
        CheckBoxUniqueRegId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxUniqueRegIdItemStateChanged(evt);
            }
        });

        btnResetFilters.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnResetFilters.setText("Reset Filters");
        btnResetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxContact)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(presentLBL)
                                    .addGap(38, 38, 38)
                                    .addComponent(lblPresent))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(absentLBL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAbsent)))
                            .addComponent(CheckBoxAddress)
                            .addComponent(CheckBoxState)
                            .addComponent(CheckBoxCountry)
                            .addComponent(CheckBoxUniqueRegId))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(387, 387, 387)
                        .addComponent(btnExit2)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(DateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(presentLBL)
                            .addComponent(lblPresent))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentLBL)
                            .addComponent(lblAbsent))
                        .addGap(28, 28, 28)
                        .addComponent(CheckBoxContact)
                        .addGap(26, 26, 26)
                        .addComponent(CheckBoxAddress)
                        .addGap(28, 28, 28)
                        .addComponent(CheckBoxState)
                        .addGap(26, 26, 26)
                        .addComponent(CheckBoxCountry)
                        .addGap(28, 28, 28)
                        .addComponent(CheckBoxUniqueRegId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void CheckBoxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxAddressActionPerformed

    private void btnResetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFiltersActionPerformed
        txtSearch.setText("");
        DateChooserFrom.setDate(null);
        DateChooserTo.setDate(null);
        CheckBoxContact.setSelected(false);
        CheckBoxAddress.setSelected(false);
        CheckBoxState.setSelected(false);
        CheckBoxCountry.setSelected(false);
        CheckBoxUniqueRegId.setSelected(false);

        loadDataInTable();
    }//GEN-LAST:event_btnResetFiltersActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void CheckBoxContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxContactItemStateChanged
        loadDataInTable(); 
    }//GEN-LAST:event_CheckBoxContactItemStateChanged

    private void CheckBoxAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxAddressItemStateChanged
         loadDataInTable();
    }//GEN-LAST:event_CheckBoxAddressItemStateChanged

    private void CheckBoxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxStateItemStateChanged
       loadDataInTable();
    }//GEN-LAST:event_CheckBoxStateItemStateChanged

    private void CheckBoxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxCountryItemStateChanged
         loadDataInTable();
    }//GEN-LAST:event_CheckBoxCountryItemStateChanged

    private void CheckBoxUniqueRegIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxUniqueRegIdItemStateChanged
         loadDataInTable();
    }//GEN-LAST:event_CheckBoxUniqueRegIdItemStateChanged

    private void DateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooserFromPropertyChange
         loadDataInTable();
    }//GEN-LAST:event_DateChooserFromPropertyChange

    private void DateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooserToPropertyChange
         loadDataInTable();
    }//GEN-LAST:event_DateChooserToPropertyChange

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
         loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxAddress;
    private javax.swing.JCheckBox CheckBoxContact;
    private javax.swing.JCheckBox CheckBoxCountry;
    private javax.swing.JCheckBox CheckBoxState;
    private javax.swing.JCheckBox CheckBoxUniqueRegId;
    private com.toedter.calendar.JDateChooser DateChooserFrom;
    private com.toedter.calendar.JDateChooser DateChooserTo;
    private javax.swing.JLabel absentLBL;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnResetFilters;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel presentLBL;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTable userTabel;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {
        List<String> columns = new ArrayList<>(Arrays.asList(
                "ID", "Name", "Gender", "Email", "Date", "CheckIn", "CheckOut", "workDuration"
        ));
        String searchText = txtSearch.getText().toString();
        Date fromDateFromCal = DateChooserFrom.getDate();
        LocalDate fromDate = null;
        if (fromDateFromCal != null) {
            fromDate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        Date toDateFromCal = DateChooserTo.getDate();
        LocalDate toDate = null;
        if (toDateFromCal != null) {
            toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        }

        Long daysBetween = null;
        if (fromDate != null && toDate != null) {
            daysBetween = countWeekdays(fromDate, toDate);
        }
        Boolean contactIncluded = CheckBoxContact.isSelected();
        Boolean AddressIncluded = CheckBoxAddress.isSelected();
        Boolean StateIncluded = CheckBoxState.isSelected();
        Boolean CountryIncluded = CheckBoxCountry.isSelected();
        Boolean uniqueRegIdIncluded = CheckBoxUniqueRegId.isSelected();

        String sqlQuery = "SELECT ud.id,ud.name,ud.gender,ud.email, ua.date,ua.checkin,ua.checkout,ua.workduration";
        if (contactIncluded) {
            columns.add("Contact");
            sqlQuery += ", ud.contact";
        }
        if (AddressIncluded) {
            columns.add("Address");
            sqlQuery += ", ud.Address";
        }
        if (StateIncluded) {
            columns.add("State");
            sqlQuery += ", ud.state";
        }
        if (CountryIncluded) {
            columns.add("Country");
            sqlQuery += ", ud.Country";
        }
        if (uniqueRegIdIncluded) {
            columns.add("UniqueRegId");
            sqlQuery += ", ud.UniqueRegId";
        }
        sqlQuery += " From userdetails AS ud INNER JOIN userattendance AS ua ON ud.id = ua.userid ";
        if (searchText != null) {
            sqlQuery += "where(ud.name like '%" + searchText + "%'or ud.email like '%" + searchText + "%') ";
            if (fromDate != null && toDate != null) {
                sqlQuery += "AND ua.date BETWEEN '" + fromDate + "' AND '" + toDate + "'";
            } else if (fromDate != null) {
                sqlQuery += "AND ua.date = '" + fromDate + "'";
            }
        } else {
            if (fromDate != null && toDate != null) {
                sqlQuery += "where ua.date BETWEEN '" + fromDate + "' AND '" + toDate + "'";
            } else if (fromDate != null) {
                sqlQuery += "where ua.date = '" + fromDate + "'";
            }
        }

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        userTabel.setModel(model);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqlQuery);
            Long presentCount = 0l;
            Long absentCount = 0l;
            Set<String> emailList = new HashSet<>();
            while (rs.next()) {
                List<Object> row = new ArrayList<>();
                row.add(rs.getString("id"));
                row.add(rs.getString("name"));
                row.add(rs.getString("gender"));
                row.add(rs.getString("email"));
                emailList.add(rs.getString("email"));
                row.add(rs.getString("date"));
                row.add(rs.getString("checkin"));
                row.add(rs.getString("checkout"));
                row.add(rs.getString("workduration"));
                if (contactIncluded) {
                    row.add(rs.getString("contact"));
                }
                if (AddressIncluded) {
                    row.add(rs.getString("Address"));
                }
                if (StateIncluded) {
                    row.add(rs.getString("State"));
                }
                if (CountryIncluded) {
                    row.add(rs.getString("Country"));
                }
                if (uniqueRegIdIncluded) {
                    row.add(rs.getString("UniqueRegId"));
                }

                if (rs.getString("checkIn") == null) {
                    absentCount++;
                } else {
                    presentCount++;
                }
                model.addRow(row.toArray());
            }

            if (emailList.size() == 1) {
                lblPresent.setVisible(true);
                lblAbsent.setVisible(true);
                presentLBL.setVisible(true);
                absentLBL.setVisible(true);
                lblPresent.setText(presentCount.toString());
                if (daysBetween != null && daysBetween > 0) {
                    absentCount = daysBetween - presentCount;

                }
                lblAbsent.setText(absentCount.toString());

            } else {
                lblPresent.setVisible(false);
                lblAbsent.setVisible(false);
                presentLBL.setVisible(false);
                absentLBL.setVisible(false);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong!!");
        }

    }

    private Long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while (date.isBefore(end) || date.equals(end)) {
            if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
                count++;
            }
            date = date.plusDays(1);

        }
        return count;
    }
}
